### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by fwd079** [FahadYousafMahar/chromeurdu#1]
Doesn't work on Chrome. See below images.

**Facebook:** 

![image](https://user-images.githubusercontent.com/7912632/96159731-eb802480-0f0c-11eb-9f62-2629bc6db974.png)

**BBC:** 

![image](https://user-images.githubusercontent.com/7912632/96159848-0eaad400-0f0d-11eb-9aa2-4f8d73ae864c.png)

Regards

**Comment by FahadYousafMahar** [comment]
Updated to ver 3.0.0 
FB and BBC are working now.
